"""Embed the unmodified Tandy2K pixel font in the UI renderer."""
from pathlib import Path
import argparse
import hashlib

ROOT = Path(__file__).resolve().parents[1]


def render():
    parts = ["/* Generated by tools/embed_ui_fonts.py --write.\n"
             " * Px437 Tandy2K, Oldschool PC Font Pack 2.2, (c) 2016-2020 VileR.\n"
             " * CC BY-SA 4.0; see third_party/tandy2k/LICENSE.txt and README.md. */\n"]
    font = ROOT / "third_party" / "tandy2k" / "Px437_Tandy2K.ttf"
    data = font.read_bytes()
    parts.append(f"/* {font.name}: SHA-256 {hashlib.sha256(data).hexdigest()} */\n")
    parts.append("static const unsigned char g_ui_tandy_font[] = {\n")
    parts.extend("    " + ",".join(f"0x{x:02x}" for x in data[i:i + 24]) + ",\n"
                 for i in range(0, len(data), 24))
    parts.append("};\n")
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    header = ROOT / "third_party" / "tandy2k" / "ui_fonts.h"
    output = render()
    if args.write:
        header.write_text(output, encoding="utf-8", newline="\n")
    elif not header.is_file() or header.read_text(encoding="utf-8") != output:
        parser.exit(1, "UI font header is stale; run python tools/embed_ui_fonts.py --write\n")
    print("Bundled Tandy2K font integrity: OK")


if __name__ == "__main__":
    main()
