"""Validate the embedded UI library; pass --write after editing ui_helpers.lua."""
from pathlib import Path
import argparse
import json

ROOT = Path(__file__).resolve().parents[1]

def render(source):
    if not source.endswith("\n"):
        raise ValueError("ui_helpers.lua must end with a newline")
    if any(ord(char) < 32 and char not in "\n\t\r" for char in source):
        raise ValueError("ui_helpers.lua contains an unsupported control character")
    return (
        "#ifndef YULE_UI_HELPERS_H\n#define YULE_UI_HELPERS_H\n\n"
        "/* Generated by tools/embed_ui_helpers.py --write. Edit ui_helpers.lua. */\n"
        "static const char k_mod_ui_helpers_lua[] =\n"
        + "".join("    " + json.dumps(line, ensure_ascii=False) + "\n"
                  for line in source.splitlines(keepends=True))
        + "    ;\n\n#endif\n"
    )

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate the checked-in C header")
    args = parser.parse_args()
    output = render((ROOT / "ui_helpers.lua").read_text(encoding="utf-8"))
    header = ROOT / "ui_helpers.h"
    if args.write:
        header.write_text(output, encoding="utf-8", newline="\n")
    elif not header.exists() or header.read_text(encoding="utf-8") != output:
        parser.exit(1, "UI header is stale. Run python tools/embed_ui_helpers.py --write\n")
    print("embedded UI source/header synchronization: OK")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
